# FILE START: .github/workflows/docker-publish.yml
name: Docker Build and Push

# Триггеры для запуска workflow:
on:
  push:
    branches:
      - master # Запускать при пуше в ветку main
    tags:
      - 'v*.*.*' # Запускать при создании тега вида v1.2.3
  pull_request:
    branches:
      - main # Запускать при создании/обновлении PR в main (только сборка, без push)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Нужно для checkout
      packages: write # Нужно для push в GitHub Container Registry (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        # Логинимся только если это не PR и не просто пуш в main (а пуш тега 'v*')
        # или если это пуш в main (для тега latest)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Или github.repository_owner
          password: ${{ secrets.GHCR_ACTION_TOKEN }} # Используем встроенный токен

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Формат: ghcr.io/USERNAME/REPO_NAME
          tags: |
            # Пуш в main -> тег latest
            type=raw,value=latest,enable={{is_default_branch}}
            # Пуш тега вида v1.2.3 -> тег v1.2.3 и v1.2 и v1
            type=semver,pattern={{version}}
            # Пуш тега вида v1.2.3 -> тег 1.2.3 и 1.2 и 1 (без 'v')
            type=semver,pattern={{version}},value={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{version}},value={{major}}.{{minor}}
            type=semver,pattern={{version}},value={{major}}
            # Для всех событий можно добавлять тег с SHA коммита
            type=sha,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Собирать из корня репозитория
          file: ./Dockerfile # Путь к Dockerfile
          push: ${{ github.event_name != 'pull_request' }} # Не пушим для PR
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Используем кэш GitHub Actions
          cache-to: type=gha,mode=max # Сохраняем кэш

# FILE END: .github/workflows/docker-publish.yml
